name: Build and Deploy to Azure Function App

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COSMOS_DB_URL: ${{ secrets.COSMOS_DB_URL }}
      COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.1.6
      id: fa
      with:
        app-name: sy4azureresume-visitorcount
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Logout of Azure CLI'
      run: |
        az logout
