name: Build and Deploy to Azure Function App

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COSMOS_DB_URL: ${{ secrets.COSMOS_DB_URL }}
      COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './sy4fsresume'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.5.1
      id: fa
      with:
        app-name: sy4faresume
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Logout of Azure CLI'
      run: |
        az logout
